version: "3.8"

services:
  backend:
    image: rexhonz77/surge-gram-backend:latest
    container_name: surge-gram-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb+srv://isuruherath0:bWnI4RdJfopkue6z@research.uhh45hr.mongodb.net/surgegram?retryWrites=true&w=majority"
      JWT_SECRET: "secretkey"
      PORT: 3000

  frontend:
    image: rexhonz77/surge-gram-frontend:latest
    container_name: surge-gram-frontend
    restart: always
    ports:
      - "5001:80"
    environment:
      REACT_APP_BACKEND_URL: http://localhost:3000
