export const styles = {
    container: { display: "flex", height: "100vh" },
    leftPanel: {
      flex: 1,
      padding: "20px",
      borderRight: "1px solid #ccc",
      display: "flex",
      flexDirection: "row",
      alignItems: "flex-start",
      gap: "15px",
      boxSizing: "border-box",
    },
    logo: { width: "100px", height: "100px", borderRadius: "50%" },
    title: { fontSize: "32px", fontWeight: "bold", color: "#444", letterSpacing: "1px" },
    middlePanel: { flex: 2, overflowY: "scroll", padding: "20px", boxSizing: "border-box" },
    filterSection: {
      display: "flex",
      justifyContent: "flex-end",
      marginBottom: "20px",
      gap: "10px",
    },
    filterButton: (isActive) => ({
      padding: "10px",
      border: "1px solid #ccc",
      borderRadius: "5px",
      backgroundColor: isActive ? "#ddd" : "#fff",
      cursor: "pointer",
    }),
    postContainer: { boxShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)", borderRadius: "2px", marginBottom: "30px" },
    postImage: { width: "100%" },
    postFooter: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "5px",
    },
    likesSection: { display: "flex", alignItems: "center", gap: "5px" },
    username: { fontWeight: "bold", fontSize: "14px" },
    date: { fontSize: "12px", color: "#888" },
    rightPanel: {
      flex: 1,
      padding: "20px",
      borderLeft: "1px solid #ccc",
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-end",
      boxSizing: "border-box",
    },
    userDetails: {
      display: "flex",
      alignItems: "center",
      marginBottom: "20px",
      width: "50%",
      boxShadow: "0px 4px 6px rgba(0, 0, 0, 0.1)",
      borderRadius: "6px",
    },
    userImage: { width: "60px", height: "60px", borderRadius: "60%", marginRight: "10px", marginLeft: "10px" },
    userName: { fontWeight: "bold", fontSize: "20px", marginBottom: "5px" },
    usernameHandle: { fontSize: "14px", color: "#888", marginTop: "0px" },
    logoutButton: {
      backgroundColor: "#ff6666",
      color: "#fff",
      border: "none",
      padding: "10px 20px",
      borderRadius: "5px",
      cursor: "pointer",
      width: "50%",
    },
  };
