name: Build, Push, and Deploy Docker Images

on:
  push:
    branches:
      - main # Trigger only on push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd Backend
          npm install
          cd ..

      - name: Run backend tests
        run: |
          cd Backend
          npm run test  # Run the backend unit tests
          cd ..

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
                       --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
                       --build-arg PORT=5000 \
                       -t ${{ secrets.DOCKER_USERNAME }}/surge-gram-backend:latest ./Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/surge-gram-backend:latest

      - name: Build and push frontend image
        run: |
          docker build --build-arg REACT_APP_BACKEND_URL=http://localhost:5000 \
                       -t ${{ secrets.DOCKER_USERNAME }}/surge-gram-frontend:latest ./Surge-gram-App
          docker push ${{ secrets.DOCKER_USERNAME }}/surge-gram-frontend:latest

  run_build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create docker-compose.yml
        run: |
          echo "version: '3.8'

          services:
            backend:
              image: '${{ secrets.DOCKER_USERNAME }}/surge-gram-backend:latest'
              container_name: surge-gram-backend
              restart: always
              ports:
                - '3000:3000'
              environment:
                MONGO_URI: '${{ secrets.MONGO_URI }}'
                JWT_SECRET: '${{ secrets.JWT_SECRET }}'
                PORT: '5000'

            frontend:
              image: '${{ secrets.DOCKER_USERNAME }}/surge-gram-frontend:latest'
              container_name: surge-gram-frontend
              restart: always
              ports:
                - '5001:80'
              environment:
                REACT_APP_BACKEND_URL: 'http://localhost:5000'" > docker-compose.yml

      - name: Display docker-compose.yml
        run: |
          cat docker-compose.yml

      # - name: Pull and run services with Docker Compose
      #   run: |
      #     docker-compose pull  # Pull images from Docker Hub
      #     docker-compose up -d  # Start the application in detached mode
