name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main # Trigger only on push to the main branch

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd Backend
          npm install
          cd ..

      - name: Run backend tests
        run: |
          cd Backend
          npm run test  # Run the backend unit tests
          cd ..

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push backend image
        run: |
          docker build --build-arg MONGO_URI=${{ secrets.MONGO_URI }} \
                       --build-arg JWT_SECRET=${{ secrets.JWT_SECRET }} \
                       --build-arg PORT=${{ secrets.PORT }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/surge-gram-backend:latest ./Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/surge-gram-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/surge-gram-frontend:latest ./Surge-gram-App
          docker push ${{ secrets.DOCKER_USERNAME }}/surge-gram-frontend:latest
